### ISSUE TITLE
file css/main.css are missed

### ISSUE THREAD

**Issue by oknemi** [krimeano/virwar#1]
The file css/main.css are missed. The folder "css" contains undesirable index.html.

**Comment by alexanderMykhailenko** [comment]
+1

**Comment by krimeano** [comment]
1) css/main.css can be generated from less/main.less
2) what's wrong with having an empty index.html?

**Comment by oknemi** [comment]
generating css file is not cuttinge edge technology. please add gupl, grunt, webpack or npm init file with instructions

**Comment by krimeano** [comment]
Added instructions to the README.md file

**Comment by alexanderMykhailenko** [comment]
Thanks,

Probably you can deploy this project to some free hosting for tests? And add link to Readme.md

**Comment by krimeano** [comment]
http://krimeano.info/virus-war/
